<?php
if (!defined('ABSPATH')) {
    exit;
}

$grid_columns = isset($context['shortcode']['layout_columns']) ? (int) $context['shortcode']['layout_columns'] : 3;
$grid_columns = max(1, min(6, $grid_columns));
$display_fields = MA_Author_List::normalize_author_list_display_fields(
    isset($context['shortcode']['display_fields']) ? $context['shortcode']['display_fields'] : [],
    $context['layout']
);
$display_field_definitions = MA_Author_List::get_author_list_display_fields();
?>
<div class="pp-multiple-authors-wrapper pp-multiple-authors-grid alignwide <?php echo esc_attr($context['css_class']); ?> pp-multiple-authors-layout-<?php echo esc_attr($context['layout']); ?>">
    <?php if (!empty($context['search_box_html'])) : ?>
        <?php echo $context['search_box_html']; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
    <?php endif; ?>

    <ul class="ppma-author-grid-list" style="--ppma-author-grid-columns: <?php echo esc_attr($grid_columns); ?>;">
        <?php foreach ($context['results'] as $index => $author) : ?>
            <li class="ppma-author-grid-card author_index_<?php echo esc_attr($index); ?> author_<?php echo esc_attr($author->slug); ?>">
                <div class="ppma-author-grid-avatar">
                    <a href="<?php echo esc_url($author->link); ?>" title="<?php echo esc_attr($author->display_name); ?>">
                        <?php echo $author->get_avatar(72); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Avatar HTML is generated by WordPress and the Author object. ?>
                    </a>
                </div>

                <h4 class="ppma-author-grid-name">
                    <a href="<?php echo esc_url($author->link); ?>" class="<?php echo esc_attr($context['item_class']); ?>" rel="author" title="<?php echo esc_attr($author->display_name); ?>">
                        <?php echo esc_html($author->display_name); ?>
                    </a>
                </h4>

                <?php if (!empty($display_fields)) : ?>
                    <dl class="ppma-author-list-fields ppma-author-grid-fields">
                        <?php foreach ($display_fields as $field_name) : ?>
                            <?php
                            $field_html = MA_Author_List::render_author_list_display_field(
                                $author,
                                $field_name,
                                $display_field_definitions[$field_name],
                                $context['layout']
                            );
                            ?>
                            <?php if ($field_html !== '') : ?>
                                <div class="ppma-author-list-field ppma-author-list-field-<?php echo esc_attr(sanitize_html_class($field_name)); ?>">
                                    <dt><?php echo esc_html($display_field_definitions[$field_name]['label']); ?></dt>
                                    <dd><?php echo $field_html; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped in MA_Author_List::render_author_list_display_field(). ?></dd>
                                </div>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </dl>
                <?php endif; ?>

                <a class="ppma-author-grid-link" href="<?php echo esc_url($author->link); ?>">
                    <?php esc_html_e('View all posts', 'publishpress-authors'); ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>

    <?php if ($context['pagination']) : ?>
        <nav class="author-boxes-footer-navigation footer-navigation navigation pagination">
            <div class="nav-links">
            <?php echo $context['pagination']; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
            </div>
        </nav>
    <?php endif; ?>
</div>
