<?php
if (!defined('ABSPATH')) {
    exit;
}
?>
<div class="pp-multiple-authors-wrapper pp-multiple-authors-table alignwide <?php echo esc_attr($context['css_class']); ?> pp-multiple-authors-layout-<?php echo esc_attr($context['layout']); ?>">
    <?php if (!empty($context['search_box_html'])) : ?>
        <?php echo $context['search_box_html']; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
    <?php endif; ?>

    <div class="ppma-author-table-wrap">
        <table>
            <thead>
                <tr>
                    <th scope="col"><?php esc_html_e('Author', 'publishpress-authors'); ?></th>
                    <th scope="col"><?php esc_html_e('Bio', 'publishpress-authors'); ?></th>
                    <th scope="col"><?php esc_html_e('Posts', 'publishpress-authors'); ?></th>
                    <th scope="col"><?php esc_html_e('Website', 'publishpress-authors'); ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($context['results'] as $index => $author) : ?>
                    <?php
                    $author_term = $author->getTerm();
                    $post_count  = isset($author_term->count) ? (int) $author_term->count : 0;
                    ?>
                    <tr class="author_index_<?php echo esc_attr($index); ?> author_<?php echo esc_attr($author->slug); ?>">
                        <td>
                            <div class="ppma-author-table-author">
                                <a href="<?php echo esc_url($author->link); ?>" title="<?php echo esc_attr($author->display_name); ?>">
                                    <?php echo $author->get_avatar(40); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Avatar HTML is generated by WordPress and the Author object. ?>
                                </a>
                                <a href="<?php echo esc_url($author->link); ?>" class="<?php echo esc_attr($context['item_class']); ?>" rel="author" title="<?php echo esc_attr($author->display_name); ?>">
                                    <?php echo esc_html($author->display_name); ?>
                                </a>
                            </div>
                        </td>
                        <td>
                            <?php $description = $author->get_description(140); ?>
                            <?php if (!empty($description)) : ?>
                                <?php echo wp_kses_post(wpautop($description)); ?>
                            <?php else : ?>
                                &mdash;
                            <?php endif; ?>
                        </td>
                        <td><?php echo esc_html(number_format_i18n($post_count)); ?></td>
                        <td>
                            <?php if (!empty($author->user_url)) : ?>
                                <a href="<?php echo esc_url($author->user_url); ?>" rel="nofollow">
                                    <?php esc_html_e('Visit website', 'publishpress-authors'); ?>
                                </a>
                            <?php else : ?>
                                &mdash;
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <?php if ($context['pagination']) : ?>
        <nav class="author-boxes-footer-navigation footer-navigation navigation pagination">
            <div class="nav-links">
            <?php echo $context['pagination']; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
            </div>
        </nav>
    <?php endif; ?>
</div>
