<?php
if (!defined('ABSPATH')) {
    exit;
}

$display_fields = MA_Author_List::normalize_author_list_display_fields(
    isset($context['shortcode']['display_fields']) ? $context['shortcode']['display_fields'] : [],
    $context['layout']
);
$display_field_definitions = MA_Author_List::get_author_list_display_fields();
?>
<div class="pp-multiple-authors-wrapper pp-multiple-authors-table alignwide <?php echo esc_attr($context['css_class']); ?> pp-multiple-authors-layout-<?php echo esc_attr($context['layout']); ?>">
    <?php if (!empty($context['search_box_html'])) : ?>
        <?php echo $context['search_box_html']; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
    <?php endif; ?>

    <div class="ppma-author-table-wrap">
        <table>
            <thead>
                <tr>
                    <th scope="col"><?php esc_html_e('Author', 'publishpress-authors'); ?></th>
                    <?php foreach ($display_fields as $field_name) : ?>
                        <th scope="col"><?php echo esc_html($display_field_definitions[$field_name]['label']); ?></th>
                    <?php endforeach; ?>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($context['results'] as $index => $author) : ?>
                    <tr class="author_index_<?php echo esc_attr($index); ?> author_<?php echo esc_attr($author->slug); ?>">
                        <td>
                            <div class="ppma-author-table-author">
                                <a href="<?php echo esc_url($author->link); ?>" title="<?php echo esc_attr($author->display_name); ?>">
                                    <?php echo $author->get_avatar(40); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Avatar HTML is generated by WordPress and the Author object. ?>
                                </a>
                                <a href="<?php echo esc_url($author->link); ?>" class="<?php echo esc_attr($context['item_class']); ?>" rel="author" title="<?php echo esc_attr($author->display_name); ?>">
                                    <?php echo esc_html($author->display_name); ?>
                                </a>
                            </div>
                        </td>
                        <?php foreach ($display_fields as $field_name) : ?>
                            <?php
                            $field_html = MA_Author_List::render_author_list_display_field(
                                $author,
                                $field_name,
                                $display_field_definitions[$field_name],
                                $context['layout']
                            );
                            ?>
                            <td class="ppma-author-list-field-<?php echo esc_attr(sanitize_html_class($field_name)); ?>">
                                <?php if ($field_html !== '') : ?>
                                    <?php echo $field_html; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped in MA_Author_List::render_author_list_display_field(). ?>
                                <?php else : ?>
                                    &mdash;
                                <?php endif; ?>
                            </td>
                        <?php endforeach; ?>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <?php if ($context['pagination']) : ?>
        <nav class="author-boxes-footer-navigation footer-navigation navigation pagination">
            <div class="nav-links">
            <?php echo $context['pagination']; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
            </div>
        </nav>
    <?php endif; ?>
</div>
