<?php
if (!defined('ABSPATH')) {
    exit;
}

$grid_columns = isset($context['shortcode']['layout_columns']) ? (int) $context['shortcode']['layout_columns'] : 3;
$grid_columns = max(1, min(6, $grid_columns));
?>
<div class="pp-multiple-authors-wrapper pp-multiple-authors-grid alignwide <?php echo esc_attr($context['css_class']); ?> pp-multiple-authors-layout-<?php echo esc_attr($context['layout']); ?>">
    <?php if (!empty($context['search_box_html'])) : ?>
        <?php echo $context['search_box_html']; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
    <?php endif; ?>

    <ul class="ppma-author-grid-list" style="--ppma-author-grid-columns: <?php echo esc_attr($grid_columns); ?>;">
        <?php foreach ($context['results'] as $index => $author) : ?>
            <li class="ppma-author-grid-card author_index_<?php echo esc_attr($index); ?> author_<?php echo esc_attr($author->slug); ?>">
                <div class="ppma-author-grid-avatar">
                    <a href="<?php echo esc_url($author->link); ?>" title="<?php echo esc_attr($author->display_name); ?>">
                        <?php echo $author->get_avatar(72); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Avatar HTML is generated by WordPress and the Author object. ?>
                    </a>
                </div>

                <h4 class="ppma-author-grid-name">
                    <a href="<?php echo esc_url($author->link); ?>" class="<?php echo esc_attr($context['item_class']); ?>" rel="author" title="<?php echo esc_attr($author->display_name); ?>">
                        <?php echo esc_html($author->display_name); ?>
                    </a>
                </h4>

                <?php $description = $author->get_description(180); ?>
                <?php if (!empty($description)) : ?>
                    <div class="ppma-author-grid-description">
                        <?php echo wp_kses_post(wpautop($description)); ?>
                    </div>
                <?php endif; ?>

                <a class="ppma-author-grid-link" href="<?php echo esc_url($author->link); ?>">
                    <?php esc_html_e('View all posts', 'publishpress-authors'); ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>

    <?php if ($context['pagination']) : ?>
        <nav class="author-boxes-footer-navigation footer-navigation navigation pagination">
            <div class="nav-links">
            <?php echo $context['pagination']; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
            </div>
        </nav>
    <?php endif; ?>
</div>
