#!/usr/bin/env bash

# This command requires to be logged in on Docker Hub. Check `docker login --help` for more information.
DOCKER_HOST_IP="" docker buildx build --platform linux/amd64,linux/arm64 --push -t publishpress/dev-workspace-terminal:authors-free ./docker
